// Murray's FSM - Notifications Service
// =======================================
// Notification creation, counting, and type constants

import type { Notification } from '@murray-fsm/shared';

// ============================================================================
// Notification Type Constants
// ============================================================================

export const NOTIFICATION_TYPES = {
  JOB_ASSIGNED: 'job_assigned',
  JOB_COMPLETED: 'job_completed',
  ESTIMATE_APPROVED: 'estimate_approved',
  REVIEW_RECEIVED: 'review_received',
  LOW_STOCK: 'low_stock',
  AGREEMENT_EXPIRING: 'agreement_expiring',
  CAMPAIGN_COMPLETED: 'campaign_completed',
} as const;

// ============================================================================
// Notification Creation
// ============================================================================

/**
 * Build a notification object ready for insertion.
 * The id and created_at fields are generated by the database.
 */
export function createNotification(params: {
  owner_id: string;
  title: string;
  body?: string;
  type: string;
  entity_type?: string;
  entity_id?: string;
}): Omit<Notification, 'id' | 'created_at'> {
  return {
    owner_id: params.owner_id,
    title: params.title,
    body: params.body ?? null,
    type: params.type,
    entity_type: params.entity_type ?? null,
    entity_id: params.entity_id ?? null,
    is_read: false,
    read_at: null,
  };
}

// ============================================================================
// Unread Count
// ============================================================================

/**
 * Count the number of unread notifications.
 */
export function getUnreadCount(notifications: Notification[]): number {
  return notifications.filter((n) => !n.is_read).length;
}
