// Murray's FSM - Notifications Service
// =======================================
// Notification creation, counting, grouping, sorting, and type constants

import type { Notification } from '@murray-fsm/shared';
import {
  parseISO,
  isToday,
  isYesterday,
  isThisWeek,
  format,
} from 'date-fns';

// ============================================================================
// Notification Type Constants
// ============================================================================

export const NOTIFICATION_TYPES = {
  job_created: { label: 'New Job', icon: 'briefcase' },
  job_assigned: { label: 'Job Assigned', icon: 'user-plus' },
  job_completed: { label: 'Job Completed', icon: 'check-circle' },
  estimate_approved: { label: 'Estimate Approved', icon: 'file-check' },
  estimate_rejected: { label: 'Estimate Rejected', icon: 'file-x' },
  review_received: { label: 'New Review', icon: 'star' },
  low_stock: { label: 'Low Stock Alert', icon: 'alert-triangle' },
  agreement_expiring: { label: 'Agreement Expiring', icon: 'clock' },
  payment_received: { label: 'Payment Received', icon: 'dollar-sign' },
  campaign_completed: { label: 'Campaign Complete', icon: 'mail-check' },
} as const;

export type NotificationType = keyof typeof NOTIFICATION_TYPES;

// ============================================================================
// Types
// ============================================================================

export interface CreateNotificationParams {
  owner_id: string;
  title: string;
  body?: string;
  type: string;
  entity_type?: string;
  entity_id?: string;
}

export interface GroupedNotifications {
  today: Notification[];
  yesterday: Notification[];
  thisWeek: Notification[];
  older: Notification[];
}

// ============================================================================
// Notification Creation
// ============================================================================

/**
 * Build a notification object ready for insertion.
 *
 * The id and created_at fields are generated by the database, so they
 * are omitted from the returned object.
 *
 * @param params - Notification parameters (title, body, type, entity info)
 * @returns A notification object without id or created_at
 */
export function createNotification(
  params: CreateNotificationParams
): Omit<Notification, 'id' | 'created_at'> {
  return {
    owner_id: params.owner_id,
    title: params.title,
    body: params.body ?? null,
    type: params.type,
    entity_type: params.entity_type ?? null,
    entity_id: params.entity_id ?? null,
    is_read: false,
    read_at: null,
  };
}

// ============================================================================
// Unread Count
// ============================================================================

/**
 * Count the number of unread notifications.
 *
 * @param notifications - Array of notifications to count
 * @returns Number of notifications where is_read is false
 */
export function getUnreadCount(notifications: Notification[]): number {
  return notifications.filter((n) => !n.is_read).length;
}

// ============================================================================
// Group by Date
// ============================================================================

/**
 * Group notifications into date-based buckets: Today, Yesterday, This Week, Older.
 *
 * Within each bucket, notifications maintain their original order.
 *
 * @param notifications - Array of notifications to group
 * @returns Object with four arrays: today, yesterday, thisWeek, older
 */
export function groupNotificationsByDate(
  notifications: Notification[]
): GroupedNotifications {
  const groups: GroupedNotifications = {
    today: [],
    yesterday: [],
    thisWeek: [],
    older: [],
  };

  for (const notification of notifications) {
    const date = parseISO(notification.created_at);

    if (isToday(date)) {
      groups.today.push(notification);
    } else if (isYesterday(date)) {
      groups.yesterday.push(notification);
    } else if (isThisWeek(date)) {
      groups.thisWeek.push(notification);
    } else {
      groups.older.push(notification);
    }
  }

  return groups;
}

// ============================================================================
// Sorting
// ============================================================================

/**
 * Sort notifications with unread items first, then by created_at descending.
 *
 * Returns a new array; the original is not mutated.
 *
 * @param notifications - Array of notifications to sort
 * @returns New sorted array
 */
export function sortNotifications(notifications: Notification[]): Notification[] {
  return [...notifications].sort((a, b) => {
    // Unread first
    if (a.is_read !== b.is_read) {
      return a.is_read ? 1 : -1;
    }

    // Then by created_at descending (newest first)
    const aTime = parseISO(a.created_at).getTime();
    const bTime = parseISO(b.created_at).getTime();
    return bTime - aTime;
  });
}
