#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Murray FSM - Supabase Environment Setup
.DESCRIPTION
    Interactive script to link your Supabase project and generate .env.local files
    for both the web dashboard and mobile app.
#>

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Murray's FSM - Supabase Setup Wizard" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Check for npx/supabase
try {
    $null = & npx supabase --version 2>$null
} catch {
    Write-Host "ERROR: Supabase CLI not found. Install with: npm install -g supabase" -ForegroundColor Red
    exit 1
}

# Step 1: Login
Write-Host "[Step 1/3] Supabase Authentication" -ForegroundColor Yellow
Write-Host "-----------------------------------------"

$tokenCheck = & npx supabase projects list 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "You need to log in to Supabase first." -ForegroundColor White
    Write-Host ""
    Write-Host "Option A: Run 'npx supabase login' (opens browser)" -ForegroundColor Gray
    Write-Host "Option B: Paste an access token below" -ForegroundColor Gray
    Write-Host "          Get one at: https://supabase.com/dashboard/account/tokens" -ForegroundColor Gray
    Write-Host ""

    $token = Read-Host "Paste your Supabase access token (or press Enter to open browser login)"

    if ([string]::IsNullOrWhiteSpace($token)) {
        Write-Host "Opening browser for login..." -ForegroundColor Cyan
        & npx supabase login
    } else {
        $env:SUPABASE_ACCESS_TOKEN = $token
        Write-Host "Token set for this session." -ForegroundColor Green
    }

    # Verify login
    $verifyCheck = & npx supabase projects list 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Login failed. Please try again." -ForegroundColor Red
        exit 1
    }
}

Write-Host "Authenticated successfully!" -ForegroundColor Green
Write-Host ""

# Step 2: List projects and let user pick
Write-Host "[Step 2/3] Select Your Supabase Project" -ForegroundColor Yellow
Write-Host "-----------------------------------------"

Write-Host "Fetching your projects..." -ForegroundColor Gray
& npx supabase projects list

Write-Host ""
$projectRef = Read-Host "Enter your project ref (the ID column above)"

if ([string]::IsNullOrWhiteSpace($projectRef)) {
    Write-Host "ERROR: Project ref is required." -ForegroundColor Red
    exit 1
}

# Step 3: Get API keys
Write-Host ""
Write-Host "[Step 3/3] Fetching API Keys" -ForegroundColor Yellow
Write-Host "-----------------------------------------"

Write-Host "Retrieving keys for project: $projectRef" -ForegroundColor Gray
$keysOutput = & npx supabase projects api-keys --project-ref $projectRef 2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Could not fetch API keys. Check your project ref." -ForegroundColor Red
    Write-Host $keysOutput
    exit 1
}

# Parse the keys from output
$anonKey = ""
$serviceRoleKey = ""

$keysString = $keysOutput | Out-String
foreach ($line in ($keysString -split "`n")) {
    if ($line -match "anon") {
        $parts = $line.Trim() -split '\s{2,}'
        foreach ($p in $parts) {
            if ($p.Trim().Length -gt 30) {
                $anonKey = $p.Trim()
            }
        }
    }
    if ($line -match "service_role") {
        $parts = $line.Trim() -split '\s{2,}'
        foreach ($p in $parts) {
            if ($p.Trim().Length -gt 30) {
                $serviceRoleKey = $p.Trim()
            }
        }
    }
}

$supabaseUrl = "https://${projectRef}.supabase.co"

if ([string]::IsNullOrWhiteSpace($anonKey)) {
    Write-Host "Could not auto-parse anon key. Raw output:" -ForegroundColor Yellow
    Write-Host $keysString
    Write-Host ""
    $anonKey = Read-Host "Paste your anon key manually"
}

Write-Host ""
Write-Host "Project URL:  $supabaseUrl" -ForegroundColor Green
if ($anonKey.Length -gt 20) {
    Write-Host "Anon Key:     $($anonKey.Substring(0, 20))..." -ForegroundColor Green
} else {
    Write-Host "Anon Key:     $anonKey" -ForegroundColor Green
}
Write-Host ""

# Ask for optional n8n webhook URL
$n8nUrl = Read-Host "n8n approval webhook URL (press Enter to skip)"
if ([string]::IsNullOrWhiteSpace($n8nUrl)) {
    $n8nUrl = "https://placeholder.com/webhook/approval-executor"
}

# Build env content as arrays of lines
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Write .env.local for web app
$webEnvPath = Join-Path $PSScriptRoot ".." "apps" "web" ".env.local"
$webLines = @(
    "# Murray's FSM Web - Environment Variables",
    "# Generated by setup-env.ps1 on $timestamp",
    "# ==========================================",
    "",
    "# Supabase",
    "NEXT_PUBLIC_SUPABASE_URL=$supabaseUrl",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=$anonKey",
    "",
    "# Site URL (for redirects)",
    "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
    "",
    "# n8n Webhooks",
    "N8N_APPROVAL_EXECUTOR_WEBHOOK_URL=$n8nUrl"
)
$webLines | Set-Content -Path $webEnvPath -Encoding UTF8
Write-Host "Web .env.local written to: $webEnvPath" -ForegroundColor Green

# Write .env for mobile app
$mobileEnvPath = Join-Path $PSScriptRoot ".." "apps" "mobile" ".env"
$mobileLines = @(
    "# Murray's FSM Mobile - Environment Variables",
    "# Generated by setup-env.ps1 on $timestamp",
    "# ==========================================",
    "",
    "# Supabase",
    "EXPO_PUBLIC_SUPABASE_URL=$supabaseUrl",
    "EXPO_PUBLIC_SUPABASE_ANON_KEY=$anonKey",
    "",
    "# Stripe (add your key here)",
    "EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder"
)
$mobileLines | Set-Content -Path $mobileEnvPath -Encoding UTF8
Write-Host "Mobile .env written to: $mobileEnvPath" -ForegroundColor Green

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Setup Complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host "  1. Restart the dev server:  pnpm dev:web" -ForegroundColor Gray
Write-Host "  2. Open: http://localhost:3001" -ForegroundColor Gray
Write-Host "  3. Sign up / log in through the app" -ForegroundColor Gray
Write-Host ""
