-- ============================================================================
-- Migration: Add customer_portal_tokens table
-- ============================================================================
-- Supports the customer self-service portal at /portal/[token].
-- Each token grants a customer (identified by phone) read access to their
-- jobs, invoices, and the ability to approve/reject estimates without
-- needing to create an account.
--
-- Tokens are generated by the business owner and sent to customers via SMS.
-- The portal page uses the Supabase anon client to look up the token, so
-- anon SELECT is intentionally allowed; the application layer validates the
-- token value and expiration before returning any customer data.
-- ============================================================================


-- ============================================================================
-- TABLE
-- ============================================================================

CREATE TABLE customer_portal_tokens (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id            UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    customer_phone      TEXT NOT NULL,
    customer_email      TEXT,
    token               TEXT NOT NULL UNIQUE,
    job_id              UUID REFERENCES jobs(id) ON DELETE SET NULL,
    expires_at          TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_accessed_at    TIMESTAMPTZ,

    -- Ensure phone is E.164 format (+1XXXXXXXXXX)
    CONSTRAINT chk_customer_phone_e164
        CHECK (customer_phone ~ '^\+[1-9]\d{1,14}$'),

    -- Ensure token is at least 32 characters
    CONSTRAINT chk_token_min_length
        CHECK (length(token) >= 32),

    -- Ensure expiration is in the future at creation time
    CONSTRAINT chk_expires_after_created
        CHECK (expires_at > created_at)
);

COMMENT ON TABLE customer_portal_tokens IS
    'Time-limited tokens granting customers read-only portal access without authentication.';
COMMENT ON COLUMN customer_portal_tokens.owner_id IS
    'The business owner (auth.users) who generated this portal token.';
COMMENT ON COLUMN customer_portal_tokens.customer_phone IS
    'Customer phone in E.164 format, used to look up their jobs and invoices.';
COMMENT ON COLUMN customer_portal_tokens.token IS
    'Crypto-random token (32+ chars) embedded in the portal URL.';
COMMENT ON COLUMN customer_portal_tokens.job_id IS
    'Optional: restricts the token to a single job context.';
COMMENT ON COLUMN customer_portal_tokens.expires_at IS
    'Token expiration timestamp, typically 30 days from creation.';
COMMENT ON COLUMN customer_portal_tokens.last_accessed_at IS
    'Updated each time the customer visits the portal with this token.';


-- ============================================================================
-- INDEXES
-- ============================================================================

-- token is already UNIQUE (btree index created by the constraint).
-- Additional indexes for common query patterns:

CREATE INDEX idx_portal_tokens_customer_phone
    ON customer_portal_tokens (customer_phone);

CREATE INDEX idx_portal_tokens_expires_at
    ON customer_portal_tokens (expires_at);

CREATE INDEX idx_portal_tokens_owner_id
    ON customer_portal_tokens (owner_id);


-- ============================================================================
-- ROW-LEVEL SECURITY
-- ============================================================================

ALTER TABLE customer_portal_tokens ENABLE ROW LEVEL SECURITY;

-- Authenticated users (business owners): full CRUD on their own tokens
CREATE POLICY "portal_tokens_authenticated_select"
    ON customer_portal_tokens FOR SELECT
    TO authenticated
    USING (owner_id = auth.uid());

CREATE POLICY "portal_tokens_authenticated_insert"
    ON customer_portal_tokens FOR INSERT
    TO authenticated
    WITH CHECK (owner_id = auth.uid());

CREATE POLICY "portal_tokens_authenticated_update"
    ON customer_portal_tokens FOR UPDATE
    TO authenticated
    USING (owner_id = auth.uid());

CREATE POLICY "portal_tokens_authenticated_delete"
    ON customer_portal_tokens FOR DELETE
    TO authenticated
    USING (owner_id = auth.uid());

-- Anon: SELECT only (portal page reads with the anon Supabase client).
-- The application layer validates the token value and checks expiration
-- before returning any customer data. No anon INSERT/UPDATE/DELETE.
CREATE POLICY "portal_tokens_anon_select"
    ON customer_portal_tokens FOR SELECT
    TO anon
    USING (true);


-- ============================================================================
-- CLEANUP GUIDANCE
-- ============================================================================
-- Expired tokens should be periodically purged to keep the table lean.
-- Recommended: delete tokens that expired more than 90 days ago.
--
--   DELETE FROM customer_portal_tokens
--   WHERE expires_at < now() - INTERVAL '90 days';
--
-- This can be run as:
--   - A Supabase pg_cron job  (e.g. daily at 03:00 UTC)
--   - A Supabase Edge Function on a cron trigger
--   - An n8n workflow on a schedule
-- ============================================================================
