-- ============================================================================
-- Migration: Add payments and invoices tables
-- ============================================================================
-- The edge function create-payment-intent already tries to INSERT into a
-- payments table that doesn't exist. This migration adds both payments
-- and invoices tables to complete the billing pipeline.
-- ============================================================================

-- ============================================================================
-- ENUM TYPES
-- ============================================================================

CREATE TYPE payment_status AS ENUM (
    'pending', 'processing', 'succeeded', 'failed', 'refunded', 'partially_refunded', 'cancelled'
);

CREATE TYPE payment_method_type AS ENUM (
    'card', 'cash', 'check', 'bank_transfer', 'other'
);

CREATE TYPE invoice_status AS ENUM (
    'draft', 'sent', 'viewed', 'paid', 'partially_paid', 'overdue', 'void', 'written_off'
);


-- ============================================================================
-- INVOICES TABLE
-- ============================================================================

CREATE TABLE invoices (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id            UUID NOT NULL,
    invoice_number      INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_id              UUID REFERENCES jobs(id) ON DELETE SET NULL,
    customer_id         UUID REFERENCES customers(id) ON DELETE SET NULL,

    -- Denormalized customer info (snapshot at invoice time)
    customer_name       TEXT,
    customer_email      TEXT,
    customer_phone      TEXT,
    customer_address    TEXT,

    status              invoice_status DEFAULT 'draft',
    issue_date          DATE DEFAULT CURRENT_DATE,
    due_date            DATE,

    subtotal_cents      INTEGER DEFAULT 0,
    tax_rate            NUMERIC(5,4) DEFAULT 0,         -- e.g. 0.0825 for 8.25%
    tax_cents           INTEGER DEFAULT 0,
    discount_cents      INTEGER DEFAULT 0,
    total_cents         INTEGER DEFAULT 0,
    amount_paid_cents   INTEGER DEFAULT 0,
    balance_due_cents   INTEGER DEFAULT 0,

    notes               TEXT,
    terms               TEXT,
    footer              TEXT,

    sent_at             TIMESTAMPTZ,
    viewed_at           TIMESTAMPTZ,
    paid_at             TIMESTAMPTZ,

    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW(),
    deleted             BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER update_invoices_updated_at
    BEFORE UPDATE ON invoices
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Invoice indexes
CREATE INDEX idx_invoices_owner_id ON invoices (owner_id);
CREATE INDEX idx_invoices_job_id ON invoices (job_id);
CREATE INDEX idx_invoices_customer_id ON invoices (customer_id);
CREATE INDEX idx_invoices_status ON invoices (status);
CREATE INDEX idx_invoices_due_date ON invoices (due_date)
    WHERE status NOT IN ('paid', 'void', 'written_off');
CREATE INDEX idx_invoices_created_at ON invoices (created_at DESC);


-- ============================================================================
-- INVOICE LINE ITEMS TABLE
-- ============================================================================

CREATE TABLE invoice_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id            UUID NOT NULL,
    invoice_id          UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    inventory_item_id   UUID REFERENCES inventory_items(id) ON DELETE SET NULL,

    name                TEXT NOT NULL,
    description         TEXT,
    qty                 NUMERIC DEFAULT 1,
    unit_price_cents    INTEGER NOT NULL,
    total_cents         INTEGER,                        -- qty * unit_price_cents
    sort_order          INTEGER DEFAULT 0,

    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW(),
    deleted             BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER update_invoice_items_updated_at
    BEFORE UPDATE ON invoice_items
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_invoice_items_invoice_id ON invoice_items (invoice_id);
CREATE INDEX idx_invoice_items_owner_id ON invoice_items (owner_id);


-- ============================================================================
-- PAYMENTS TABLE
-- ============================================================================

CREATE TABLE payments (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id                UUID NOT NULL,
    job_id                  UUID REFERENCES jobs(id) ON DELETE SET NULL,
    invoice_id              UUID REFERENCES invoices(id) ON DELETE SET NULL,

    -- Payment details
    provider                TEXT NOT NULL DEFAULT 'stripe',  -- 'stripe', 'cash', 'check', etc.
    method                  payment_method_type DEFAULT 'card',
    status                  payment_status DEFAULT 'pending',
    amount_cents            INTEGER NOT NULL,
    currency                TEXT DEFAULT 'usd',

    -- Stripe-specific fields
    stripe_payment_intent_id TEXT,
    stripe_charge_id         TEXT,
    stripe_customer_id       TEXT,
    stripe_receipt_url       TEXT,

    -- Refund tracking
    refunded_amount_cents   INTEGER DEFAULT 0,

    -- Metadata
    description             TEXT,
    metadata                JSONB DEFAULT '{}'::jsonb,
    failure_reason          TEXT,

    paid_at                 TIMESTAMPTZ,
    refunded_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    deleted                 BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER update_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Payment indexes
CREATE INDEX idx_payments_owner_id ON payments (owner_id);
CREATE INDEX idx_payments_job_id ON payments (job_id);
CREATE INDEX idx_payments_invoice_id ON payments (invoice_id);
CREATE INDEX idx_payments_status ON payments (status);
CREATE INDEX idx_payments_stripe_payment_intent_id ON payments (stripe_payment_intent_id);
CREATE INDEX idx_payments_created_at ON payments (created_at DESC);


-- ============================================================================
-- AUTO-UPDATE INVOICE TOTALS TRIGGER
-- ============================================================================

CREATE OR REPLACE FUNCTION update_invoice_totals()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE invoices
    SET
        subtotal_cents = COALESCE((
            SELECT SUM(total_cents) FROM invoice_items
            WHERE invoice_id = COALESCE(NEW.invoice_id, OLD.invoice_id)
            AND deleted = FALSE
        ), 0),
        total_cents = COALESCE((
            SELECT SUM(total_cents) FROM invoice_items
            WHERE invoice_id = COALESCE(NEW.invoice_id, OLD.invoice_id)
            AND deleted = FALSE
        ), 0) + COALESCE(tax_cents, 0) - COALESCE(discount_cents, 0),
        balance_due_cents = COALESCE((
            SELECT SUM(total_cents) FROM invoice_items
            WHERE invoice_id = COALESCE(NEW.invoice_id, OLD.invoice_id)
            AND deleted = FALSE
        ), 0) + COALESCE(tax_cents, 0) - COALESCE(discount_cents, 0) - COALESCE(amount_paid_cents, 0)
    WHERE id = COALESCE(NEW.invoice_id, OLD.invoice_id);
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_invoice_totals
    AFTER INSERT OR UPDATE OR DELETE ON invoice_items
    FOR EACH ROW EXECUTE FUNCTION update_invoice_totals();


-- ============================================================================
-- AUTO-UPDATE INVOICE PAID AMOUNT ON PAYMENT
-- ============================================================================

CREATE OR REPLACE FUNCTION update_invoice_paid_amount()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.invoice_id IS NOT NULL AND NEW.status = 'succeeded' THEN
        UPDATE invoices
        SET
            amount_paid_cents = COALESCE((
                SELECT SUM(amount_cents) FROM payments
                WHERE invoice_id = NEW.invoice_id
                AND status = 'succeeded'
                AND deleted = FALSE
            ), 0),
            balance_due_cents = total_cents - COALESCE((
                SELECT SUM(amount_cents) FROM payments
                WHERE invoice_id = NEW.invoice_id
                AND status = 'succeeded'
                AND deleted = FALSE
            ), 0),
            status = CASE
                WHEN COALESCE((
                    SELECT SUM(amount_cents) FROM payments
                    WHERE invoice_id = NEW.invoice_id
                    AND status = 'succeeded'
                    AND deleted = FALSE
                ), 0) >= total_cents THEN 'paid'::invoice_status
                WHEN COALESCE((
                    SELECT SUM(amount_cents) FROM payments
                    WHERE invoice_id = NEW.invoice_id
                    AND status = 'succeeded'
                    AND deleted = FALSE
                ), 0) > 0 THEN 'partially_paid'::invoice_status
                ELSE status
            END,
            paid_at = CASE
                WHEN COALESCE((
                    SELECT SUM(amount_cents) FROM payments
                    WHERE invoice_id = NEW.invoice_id
                    AND status = 'succeeded'
                    AND deleted = FALSE
                ), 0) >= total_cents THEN NOW()
                ELSE paid_at
            END
        WHERE id = NEW.invoice_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_invoice_paid
    AFTER INSERT OR UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION update_invoice_paid_amount();


-- ============================================================================
-- RLS POLICIES
-- ============================================================================

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- invoices: authenticated full CRUD
CREATE POLICY "invoices_authenticated_select" ON invoices FOR SELECT TO authenticated USING (true);
CREATE POLICY "invoices_authenticated_insert" ON invoices FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "invoices_authenticated_update" ON invoices FOR UPDATE TO authenticated USING (true);
CREATE POLICY "invoices_authenticated_delete" ON invoices FOR DELETE TO authenticated USING (true);

-- invoice_items: authenticated full CRUD
CREATE POLICY "invoice_items_authenticated_select" ON invoice_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "invoice_items_authenticated_insert" ON invoice_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "invoice_items_authenticated_update" ON invoice_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "invoice_items_authenticated_delete" ON invoice_items FOR DELETE TO authenticated USING (true);

-- payments: authenticated full CRUD
CREATE POLICY "payments_authenticated_select" ON payments FOR SELECT TO authenticated USING (true);
CREATE POLICY "payments_authenticated_insert" ON payments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "payments_authenticated_update" ON payments FOR UPDATE TO authenticated USING (true);
CREATE POLICY "payments_authenticated_delete" ON payments FOR DELETE TO authenticated USING (true);
